#pragma once

#include <stdbool.h>
#include <stdio.h>
#define FSAVE_STATE_TWO "m_state_tw"
#define FMISSION_2 "mission_2"
#define MISSION_TWO_HACKED "m2pwnd"
#define MISSION_TWO_YWHACK_COMPLETE "m2ywhack"
#define MISSION_TWO_CAR_BEACON 71
#define MISSION_TWO_RED_HACK_BEACON 39
#define MISSION_TWO_YWHACK_BEACONHACKED 38
#define MISSION_TWO_YWHACK_BEACON 32
#define MISSION_TWO_DESCRIPTION 19
#define MISSION_TWO_EC_HACKED_BEACON 115
#define MISSION_TWO_EC_BEACON 115
typedef enum {
  MISSION_TWO_YWH_IDLE, // Waiting for a beacon in the patagonspace village
  MISSION_TWO_RED_HACKED, // Show mission
  MISSION_TWO_CAR_BEACON_IDLE,
  MISSION_TWO_SHOW_MISSION,
  MISSION_TWO_EC_BEACON_IDLE,
} mission_two_state_t;

// 'Screenshot_2024-11-01_at_6', 32x32px
const unsigned char bitmap_michi[] = {
	0x00, 0x00, 0x07, 0xc0, 0x00, 0x00, 0x07, 0xe0, 0x00, 0x00, 0x0d, 0xe0, 0x00, 0x07, 0xfb, 0xa0, 
	0x00, 0x1f, 0xbb, 0xf0, 0x3c, 0x74, 0x01, 0xb0, 0x67, 0xd0, 0x00, 0x58, 0xfd, 0x80, 0x04, 0xf8, 
	0xfe, 0x01, 0xff, 0xf8, 0xff, 0x1f, 0xf9, 0xfc, 0x7e, 0x7f, 0xe0, 0xfc, 0x2f, 0xff, 0xe0, 0xfc, 
	0x3b, 0x83, 0xe3, 0xfe, 0x1f, 0xc5, 0xff, 0xfe, 0x1f, 0xcf, 0xff, 0xfe, 0x1b, 0xff, 0xff, 0xfe, 
	0x1f, 0xff, 0xff, 0xff, 0x15, 0xff, 0xff, 0xfb, 0x37, 0xff, 0xff, 0xfb, 0x27, 0xff, 0xff, 0xff, 
	0x23, 0xff, 0xff, 0xff, 0x27, 0xff, 0xfd, 0xff, 0x4f, 0xff, 0xff, 0xbf, 0x7f, 0xf7, 0xe7, 0xff, 
	0x7f, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xdf, 0xff, 0xff, 0xff, 0xdf, 0xff, 0xff, 0xff, 
	0xcf, 0xff, 0xff, 0xfe, 0x7f, 0xff, 0xff, 0xfe, 0x0f, 0xff, 0xff, 0xfe, 0x00, 0x3f, 0xff, 0xfc
};

char* mission_two_carhacking_beacon[MISSION_TWO_CAR_BEACON] = {
  ".. Tu vehiculo",
  "rueda por la",
  "carreta rajada",
  "tras las",
  "tormentas ...",
  "             ",
  "El cambio de",
  "las condiciones",
  "climaticas ha",
  "provocado las",
  "tormentas, que",
  "en consecuencia",
  "ha traido ",
  "da\32os a la",
  "carretera. ",
  "Pero si ",
  "hubieramos",
  "conducido",
  "menos,",
  "habriamos",
  "tenido menos",
  "impacto vas",
  "pensando en ",
  "voz alta."
  "             ",
  "-No pude",
  "evitar",
  "escucharte..."
  "             ",
  "-Una gran",
  "parte del"
  "problema es",
  "nuestra",
  "dependencia en",
  "la tecnologia ",
  "no optima. ",
  "Si tienes",
  "codigo mal",
  "escrito, tus",
  "servidores",
  "corren por"
  "mas tiempo.",
  "Si no",
  "optimizas,",
  "afecta al ",
  "rendimiento",
  "del sistema."
  "             ",
  "No seria bueno",
  "aprender mas ",
  "sobre como ",
  "corregir esos",
  "errores para",
  "minimizar el",
  "consumo",
  "energetico?",
  "- te preguntas",
  "mientras",
  "buscas a",
  "alguien que",
  "te pueda",
  "echar una"
  "mano a ",
  "comprender ",
  "mejor como",
  "gestionar los",
  "constantes",
  "errores de ",
  "codigo."
  "             ",
  "- En eso",
  "piensas en la",
  "villa de",
  "Yes We Hack",
  "             ",
  "Si, ellos",
  "tambien",
  "hackean ..."
};

char* mission_two_red_beacon_hacked[MISSION_TWO_RED_HACK_BEACON] = {
  "Mas cuidado!",
  "acabas de ser",
  "hackeado!",
  "             ",
  "Ahora tu badge",
  "esta bajo el",
  "control de",
  "un ransomware",
  "...",
  "             ",
  "Este ransomware",
  "entorpece tu",
  "sistema y",
  "te muestra",
  "texto en",
  "utilizando",
  "frases en",
  "formato aliado",
  "             ",
  "Si quieres",
  "recuperar el",
  "control de tu",
  "badge, debes",
  "resolver la",
  "mision en la",
  "villla de",
  "Yes We Hack",
  "             ",
  "             ",
  "O tal vez",
  "alguna otra",
  "villa te puede",
  "ayudar a",
  "recuperar el",
  "control de tu",
  "badge...",
  "             ",
  "No todo es",
  "red team...",
};

char* mission_two_ywhack_beacon_hacked[MISSION_TWO_YWHACK_BEACONHACKED] = {
  "Se te acerca",
  "une de les",
  "coleques",
  "hackers, ",
  "te pasa una",
  "tabla de",
  "conversion y",
  "te pide que",
  "le eches una",
  "mano a ",
  "decodificar un",
  "mensaje. ",
  "Pero no es",
  "porque el",
  "colegue no",
  "pueda, sino",
  "porque asi",
  "va la historia",
  "             ",
  "             ",
  "No tienen la",
  "tabla completa,"
  "asi que tienes"
  "que echar mano",
  "de tus",
  "conocimientos en",
  "criptografia",
  "para ",
  "descifrar el",
  "error oculto",
  "en el codigo.",
  "             ",
  "             ",
  "Como pago por",
  "el trabajo, ",
  "te dara un ",
  "add-on para",
  "tu badge.",
  "Y un codigo",
  "para la matrix."
};

char* mission_two_ywhack_beacon[MISSION_TWO_YWHACK_BEACON] = {
  "Se te acerca",
  "uno de los",
  "colegas",
  "hackers, ",
  "te pasa una",
  "tabla de",
  "conversion y",
  "te pide que",
  "le eches una",
  "mano a ",
  "decodificar un",
  "mensaje. ",
  "             ",
  "             ",
  "No tienen la",
  "tabla completa,"
  "asi que tienes"
  "que echar mano",
  "de tus",
  "conocimientos en",
  "criptografia",
  "para ",
  "descifrar el",
  "error oculto",
  "en el codigo.",
  "             ",
  "             ",
  "Como pago por",
  "el trabajo, ",
  "te dara un ",
  "add-on para",
  "tu badge.",
  "Y un codigo",
  "para la matrix."
};
// No encrypted
char* mission_two_description[MISSION_TWO_DESCRIPTION] = {
  "... El saludo",
  "secreto de la",
  "gente de",
  "Yes We Hack",
  "             ",
  "             ",
  "El saludo es",
  "tan sencillo",
  "como gritar...",
  "             ",
  "YES WE HACK!",
  "             ",
  "al llegar a su",
  "villa, asi que",
  "grita lo mas",
  "fuerte que",
  "puedas!",
  "             ",
  "- NUEVA MISION -",
};

char* mission_two_ec_beacon_hacked[MISSION_TWO_EC_HACKED_BEACON] = {
  "... en el ",
  "stand de les",
  "gatos, ",
  "todes maullan",
  "...",
  "             ",
  "             ",
  "No es broma, ",
  "se ha convertido",
  "en una costumbre.",
  "Les eCats se",
  "han envilecido",
  "y ahora maullan",
  "como si de",
  "verdad fueran",
  "mascotas peludas.",
  "Te acercas y te",
  "preguntas como",
  "puedes",
  "comunicarte",
  "con elles."
  "             ",
  "             ",
  "Recuerdas aquel",
  "gato que vivía",
  "en casa de tu",
  "abuela.",
  "Al acariciarle",
  "tras de las",
  "orejas, ",
  "ronroneaba.",
  "Quizás si te",
  "acercas en modo",
  "ronroneante,",
  "consigas algo",
  "de elles."
  "             ",
  "             ",
  "- Prrrr,",
  "prrrrmiiiaaauuu",
  "- dices primero",
  "tímidamente y",
  "luego repites",
  "cada vez más",
  "alto...",
  "             ",
  "             ",
  "Uno de los",
  "eCats gira su",
  "cabeza,",
  "olisquea el ",
  "aire y te ",
  "maulla ",
  "sonriente:",
  "             ",
  "             ",
  "- Miiiiiaaauuu",
  "prrr, prrr."
  "             ",
  "             ",
  "Mira tu badge,",
  "que llevas ",
  "colgado del ",
  "cuello, ",
  "lo manipula, ",
  "ve el add-on ",
  "y con un ",
  "marcatextos, ",
  "te escribe",
  "algo en la",
  "palma de la ",
  "mano.",
  "Tu siques ",
  "estando absorto",
  "en ver a une",
  "adulte maullar",
  "al unísono con",
  "otres, pero ya",
  "tienes lo que",
  "quieres y estas",
  "listo para",
  "marchar",
  "cuando ...",
  "             ",
  "             ",
  "... une tipe",
  "con barba te",
  "esta diciendo",
  "algo al oido ...",
  "... no lo oyes",
  "bien, respondes",
  "con un -miau-",
  "porque tienes",
  "miedo de romper",
  "la magia y que",
  "le extra\32e se",
  "marche sin",
  "enterarte el",
  "mensaje.",
  "Después de",
  "un par de",
  "repecitiones",
  "...",
  "             ",
  "             ",
  "- No seas",
  "idiote!",
  "No soy un gato!",
  "- exclama",
  "- Perdón, como",
  "lo iba yo",
  "a saber?",
  "Pero es que",
  "tanto maullar",
  "se me olvidan",
  "las cosas",
  "             ",
  "             ",
};

char* mission_two_ec_beacon[MISSION_TWO_EC_BEACON] = {
  "... en el ",
  "stand de los",
  "gatos, ",
  "todos maullan",
  "...",
  "             ",
  "             ",
  "No es broma, ",
  "se ha convertido",
  "en una costumbre.",
  "Los eCats se",
  "han envilecido",
  "y ahora maullan",
  "como si de",
  "verdad fueran",
  "mascotas peludas.",
  "Te acercas y te",
  "preguntas como",
  "puedes",
  "comunicarte",
  "con ellos."
  "             ",
  "             ",
  "Recuerdas aquel",
  "gato que vivía",
  "en casa de tu",
  "abuela.",
  "Al acariciarle",
  "tras de las",
  "orejas, ",
  "ronroneaba.",
  "Quizás si te",
  "acercas en modo",
  "ronroneante,",
  "consigas algo",
  "de ellos."
  "             ",
  "             ",
  "- Prrrr,",
  "prrrrmiiiaaauuu",
  "- dices primero",
  "tímidamente y",
  "luego repites",
  "cada vez más",
  "alto...",
  "             ",
  "             ",
  "Uno de los",
  "eCats gira su",
  "cabeza,",
  "olisquea el ",
  "aire y te ",
  "maulla ",
  "sonriente:",
  "             ",
  "             ",
  "- Miiiiiaaauuu",
  "prrr, prrr."
  "             ",
  "             ",
  "Mira tu badge,",
  "que llevas ",
  "colgado del ",
  "cuello, ",
  "lo manipula, ",
  "ve el add-on ",
  "y con un ",
  "marcatextos, ",
  "te escribe",
  "algo en la",
  "palma de la ",
  "mano.",
  "Tu siques ",
  "estando absorto",
  "en ver a une",
  "adulto maullar",
  "al unísono con",
  "otros, pero ya",
  "tienes lo que",
  "quieres y estas",
  "listo para",
  "marchar",
  "cuando ...",
  "             ",
  "             ",
  "... un tipo",
  "con barba te",
  "esta diciendo",
  "algo al oido ...",
  "... no lo oyes",
  "bien, respondes",
  "con un -miau-",
  "porque tienes",
  "miedo de romper",
  "la magia y que",
  "le extra\32e se",
  "marche sin",
  "enterarte el",
  "mensaje.",
  "Después de",
  "un par de",
  "repecitiones",
  "...",
  "             ",
  "             ",
  "- No seas",
  "idiota!",
  "No soy un gato!",
  "- exclama",
  "- Perdón, como",
  "lo iba yo",
  "a saber?",
  "Pero es que",
  "tanto maullar",
  "se me olvidan",
  "las cosas",
  "             ",
  "             ",
};




uint8_t mission_hacked_active();
void mission_two_begin(uint8_t village_idx);
void mission_two_hacked_begin(uint8_t village_idx);
void mission_two_unhack_animation();