#pragma once

#define LORA_PIN_MISO CONFIG_LORA_MISO_PIN
#define LORA_PIN_MOSI CONFIG_LORA_MOSI_PIN
#define LORA_PIN_SCK CONFIG_LORA_SCK_PIN
#define LORA_PIN_DIO0 CONFIG_LORA_DIO0_PIN
#define LORA_PIN_DIO1 CONFIG_LORA_DIO1_PIN
#define LORA_PIN_DIO2 CONFIG_LORA_DIO2_PIN
#define LORA_PIN_NSS CONFIG_LORA_NSS_PIN
#define LORA_PIN_RST CONFIG_LORA_RST_PIN

void lora_module_begin();